name: Coop Jobs

on:
  workflow_dispatch:
    inputs:
      jobSelection:
        description: 'Select a job to run'
        required: true
        type: choice
        options:
          - coop-main
          - coop-migros
          - migros-coop
          - migros-main

env:
  ECR_REPOSITORY: 043437012221.dkr.ecr.ap-south-1.amazonaws.com/coop-main
  AWS_REGION: ap-south-1
  #JOB_DEFINITION_NAME: second 
  #JOB_QUEUE: queue
  #JOB_NAME: second
  #EXECUTION_ROLE_ARN: arn:aws:iam::043437012221:role/ecsTaskExecutionRole
  #USER_NAME: root
  IMAGE_TAG: latest

jobs:
  build-push-update-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker image
        if: ${{ github.event.inputs.jobSelection }}
        run: |
          CONTEXT="${{ github.event.inputs.jobSelection }}"
          docker build -f ./coop/$CONTEXT/Dockerfile -t $ECR_REPOSITORY/$CONTEXT:$IMAGE_TAG ./coop/$CONTEXT
          docker push $ECR_REPOSITORY/$CONTEXT:$IMAGE_TAG 
