name: Manual Folder Workflow

on:
  workflow_dispatch:
    inputs:
      folderName:
        description: 'Folder to run the script in (e.g., folder1, folder2, folder3)'
        required: true
        default: 'folder1'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Run script in the specified folder
      run: |
        cd ${{ github.event.inputs.folderName }}
        node script.js
