name: Unified Docker Build and Deployment

on:
  workflow_dispatch:
    inputs:
      jobSelection:
        description: 'Select a job to run'
        required: true
        type: choice
        options:
          - coop-main
          - coop-migros
          - migros-coop
          - migros-main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context: "coop-main"
            jobName: "coop-main"
          - context: "coop-migros"
            jobName: "coop-migros"
          - context: "migros-coop"
            jobName: "migros-coop"
          - context: "migros-main"
            jobName: "migros-main"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker image
        if: ${{ github.event.inputs.jobSelection == matrix.jobName }}
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.context }}
          file: ./${{ matrix.context }}/Dockerfile
          push: true
          tags: your_repository/${{ matrix.jobName }}:latest
